module CorbaAddressBook {
	struct Contact {
		string name;
		string pnumber;
	};

	exception ContactAlreadyExists {
		Contact c;
	};
	exception ContactNotFound {};

	typedef sequence<Contact> ContactList;

	interface AddressBook {
		void addContact (in Contact c)
			raises (ContactAlreadyExists);
		void delContact (in string name)
			raises (ContactNotFound);
		void updateContact (in string currentName, in Contact updatedContact)
			raises (ContactNotFound);
		ContactList getContacts ();
	};
};
